# Generated by Django 5.0.1 on 2024-02-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('', 'Selecione o assunto'), ('dúvida', 'Dúvida'), ('sugestão', 'Sugestão'), ('reclamação', 'Reclamação'), ('outros', 'Outros')], default='', max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mensagem', models.TextField(max_length=1000)),
            ],
        ),
    ]
