# Generated by Django 5.0.1 on 2024-02-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
