# Generated by Django 5.0.1 on 2024-02-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_perfil_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
    ]
