# Generated by Django 5.0.1 on 2024-02-04 23:26

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTi', '0002_alter_post_conteudo_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_capa',
            field=models.ImageField(blank=True, upload_to='static/blog/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 20, 26, 16, 567021)),
        ),
    ]
