# Generated by Django 5.0.1 on 2024-02-04 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTi', '0004_alter_post_data_publicacao_alter_post_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 20, 56, 33, 69506)),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog/%Y/%m/%d/'),
        ),
    ]
