# Generated by Django 5.0.1 on 2024-02-09 22:14

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTi', '0021_alter_post_data_publicacao_topico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='resumo',
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 19, 14, 43, 762435)),
        ),
        migrations.AlterField(
            model_name='topico',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
