# Generated by Django 5.0.1 on 2024-02-09 22:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTi', '0025_alter_post_data_publicacao_situacao'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacao',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.perfil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 19, 32, 3, 286343)),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1024)),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.perfil')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTi.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostSituacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTi.post')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogTi.situacao')),
            ],
            options={
                'unique_together': {('post', 'situacao')},
            },
        ),
        migrations.AddField(
            model_name='situacao',
            name='posts',
            field=models.ManyToManyField(through='blogTi.PostSituacao', to='blogTi.post'),
        ),
    ]
