# Generated by Django 5.0.1 on 2024-02-09 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTi', '0026_remove_situacao_post_alter_post_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 19, 37, 22, 182929)),
        ),
    ]
