# Generated by Django 5.0.1 on 2024-02-09 23:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTi', '0030_alter_post_data_publicacao_comentario'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacao',
            name='posts',
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.perfil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 20, 29, 47, 702989)),
        ),
        migrations.DeleteModel(
            name='PostSituacao',
        ),
        migrations.DeleteModel(
            name='Situacao',
        ),
    ]
