# Generated by Django 5.0.1 on 2024-02-09 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogTi', '0033_remove_situacao_posts_alter_post_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 20, 43, 7, 913544)),
        ),
    ]
